spring:
  main:
    web-application-type: none
  cloud:
    stream:
      bindings:
        decorateGreeting-in-0:
          destination: greetingChannel
        decorateGreeting-out-0:
          destination: decoratedChannel

